# -*- coding: utf-8 -*-
"""Task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1noWLNJ8G3Zw52efBLqsnRJ1iJfb72H
"""

import sqlite3

# Connect to SQLite database (creates new file if not exists)
conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

# Create sales table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS sales (
        id INTEGER PRIMARY KEY,
        product TEXT,
        quantity INTEGER,
        price REAL
    )
''')

# Insert sample data into sales table
sales_data = [
    ('Tumbler', 100, 12.5),
    ('Notepad', 150, 8.75),
    ('Mug', 80, 10.0),
    ('Phone Case', 200, 15.25)
]

cursor.executemany('''
    INSERT INTO sales (product, quantity, price)
    VALUES (?, ?, ?)
''', sales_data)

# Commit changes and close connection
conn.commit()
conn.close()

print("Database 'sales_data.db' created and populated.")

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connect to SQLite database
conn = sqlite3.connect("sales_data.db")

# Define SQL query to get sales summary
query = '''
    SELECT product, SUM(quantity) AS total_quantity, SUM(quantity * price) AS revenue
    FROM sales
    GROUP BY product
'''

# Load data into a pandas DataFrame
df = pd.read_sql_query(query, conn)

# Print the sales summary
print("Sales Summary:")
print(df)
print()

# Plotting the data using matplotlib
df.plot(kind='bar', x='product', y='revenue', legend=False)
plt.xlabel('Product')
plt.ylabel('Revenue ($)')
plt.title('Revenue by Product')
plt.xticks(rotation=45)
plt.tight_layout()

# Save the plot as a PNG file
plt.savefig("sales_chart.png")

# Display the plot
plt.show()

# Close the connection
conn.close()